model_id: {model_id} # <-- change this to the model you want to fine-tune
train_path: {train_path} # <-- change this to the path to your training data
valid_path: {valid_path} # <-- change this to the path to your validation data. This is optional
context_length: {context_length} # <-- change this to the context length you want to use
num_devices: {num_devices} # <-- change this to total number of GPUs that you want to use
num_epochs: {num_epochs} # <-- change this to the number of epochs that you want to train for
train_batch_size_per_device: {train_batch_size_per_device} # <-- change this to the batch size per GPU
eval_batch_size_per_device: {eval_batch_size_per_device} # <-- change this to the batch size per GPU for evaluation
learning_rate: {learning_rate} # <-- change this to the learning rate that you want to use
worker_resources:
  accelerator_type:{accelerator_type}: 0.001
# The rest of the config can remain the same given it will
# work for different models and datasets 
num_checkpoints_to_keep: 1
dataset_size_scaling_factor: 10000
output_dir: /mnt/local_storage
deepspeed:
  config_path: deepspeed_config.json
flash_attention_2: true
lora_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
    - embed_tokens
    - lm_head
  task_type: "CAUSAL_LM"
  modules_to_save: []
  bias: "none"
  fan_in_fan_out: false
  init_lora_weights: true